### ISSUE TITLE
Support of sparse tensors

### ISSUE THREAD

**Issue by niknoproblems** [fastai/fastai#1105]
Can please add support of sparse tensors to tabular module. I plan to do an embedding of users with fastai lib, and I have the problem with OOM because of the sparsity of my data.

**Comment by KeremTurgutlu** [comment]
Hi I have a working prototype for this at the moment. For my use case I had BOW, TF-IDF ish representation of my data which was in scipy.sparse format and then i wrote a custom `collate_fn` for indexing sparse data, stack it and turn it into a batch. Also you need to be aware that autograd doesn't fully support all operations but it does support some which can be found here: https://github.com/pytorch/pytorch/issues/9674. With this in mind if you try `.backward()` on `nn.Linear`  after moving the parameters to a GPU it will fail since an intermediate variable is created (at least that's what i can remember from the Pytorch forums), so i ended writing a custom `nn.LinearSparse` which will allow moving variables as the module is created and uses `torch.mm` . If there is really a need for sparse support at least what can be done at the moment i would be happy to contribute what i developed so far. :)
