### ISSUE TITLE
Request for zip file download for the function "untar_data" to download datasets

### ISSUE THREAD

**Issue by gshashank84** [fastai/fastai#1142]
The function "untar_data" would be a lot helpful if it can support zip file extraction also

**Comment by stas00** [comment]
And if it does that, I can't help to notice that it's already not an un**tar** - as it handles .tgz, .tar.gz - so probably it needs to be renamed to something more honest to what it does, no?

and then we have 7zip that is becoming much more common, and bz2. 

May be there is a python module that already handles all of those formats transparently so that we don't have to reinvent the wheel. Do you mind researching that @gshashank84? The only requirement is that it either has to be a python core module or if it's an external module it has to be both on pypi and conda's main channel (not conda-forge).

**Comment by gshashank84** [comment]
yes it would certainly not have been named 'untar_data' then, its just that I could not able to find a Notebook friendly module to unzip file...

**Comment by stas00** [comment]
until then you can always:
```
! unzip file.zip
```
replace 'unzip' with whatever app you normally use on your system to unzip files.

**Comment by Boutross3** [comment]
What about [libarchive](https://github.com/libarchive/libarchive/wiki/LibarchiveFormats) ? It seems to fit the bill.

**Comment by kevinbird15** [comment]
I did something similar to what @stas00 mentioned with 

```
! unzip file.zip
```

but I wanted to put the files in a specific location that I thought might be useful to somebody else.

```
! unzip -q -j {str(filename)} -d {str(data_folder)}
```

-q = quiet mode
-j = put everything in a single directory
filename is a PosixPath of the zip file
-d = unzip to this directory
data_folder is a PosixPath of the desired directory
