### ISSUE TITLE
Invoking a callback which is not there....  AttributeError: 'NoneType' object has no attribute 'on_train_begin'

### ISSUE THREAD

**Issue by gsgbills** [fastai/fastai#117]
There are several instances of invoking a callback which is NoneType.
For example: 

for cb in callbacks: cb.on_batch_begin()
     98             loss = stepper.step(V(x),V(y))
     99             avg_loss = avg_loss * avg_mom + loss * (1-avg_mom)

AttributeError: 'NoneType' object has no attribute 'on_batch_begin'

There should be a check, e.g.,
if (cb is not None): cb.on_batch_begin()

**Comment by chasehere** [comment]
It looks to be a problem with fit_gen in learner.py when `use_wd_sched` is set to true because `self.sched` never gets set.  This is my first time looking at this repo so I'm not sure if we should change (A) `self.wd_sched = ...` to `self.sched` or (B) `self.sched` should be set in addition to `self.wd_sched`.

**Comment by jph00** [comment]
That's an early research option which isn't well tested at all. I haven't had any luck getting better results from it. So I'd suggest avoiding it, unless you're interested in being involved in that research (and if the latter, have a search for the issue which added it, so the contributor can be included in the discussion).
