### ISSUE TITLE
Incorrect .h5 file extensions for PyTorch weight files

### ISSUE THREAD

**Issue by lutzroeder** [fastai/fastai#1181]
**Describe the bug**

Files below have `.h5` extensions but do not contain valid HDF5 content.

They are saved in `torch.save` pickle format and should have a `.pth` or `.pt` extension.

http://files.fast.ai/models/cifar10_resnext32x32_8.h5
http://files.fast.ai/models/sen_32x32_8.h5
http://files.fast.ai/models/sen_32x32sen34.h5
http://files.fast.ai/models/fwd_wt103.h5
http://files.fast.ai/models/fwd_wt103_enc.h5
http://files.fast.ai/models/bwd_wt103.h5
http://files.fast.ai/models/bwd_wt103_enc.h5

**To Reproduce**

Open files in hex editor and inspect content. `0x80 0x02` is a pickle header.

**Comment by jph00** [comment]
Thanks for pointing this out. The torchvision files are from another non-fastai project - we're just keeping a copy. And we kept the other models using a consistent filename.

For fastai v1 all model files now use .pth as the extension. I don't want to rename stuff in old versions since it'll break anything that relies on them.
