### ISSUE TITLE
[Feature request] Make dependencies optional

### ISSUE THREAD

**Issue by elyase** [fastai/fastai#1194]
**Describe the bug**

Add support for optional dependencies so that people that only want to use the library for tabular don't need to install NLP / Vision dependencies. 

**Expected behavior**

`pip install fastai[nlp]` # only installs nlp dependencies (i.e. spacy, etc)
`pip install fastai[vision]` # installs Pillow, torchvision, ...
`pip install fastai[tabular,nlp]`
`pip install fastai[all]`

For an example see the [iPython project](https://github.com/ipython/ipython/blob/844ad8b98fec387399062ef373f202d891ed708d/setup.py#L174)

**Comment by stas00** [comment]
Personally, I don't think that splitting fastai into multiple packages, to support conda's lack of optional dependencies, is the best idea. As it would create a confusion about with different non-matching version numbers for each sub-package and the main package, as most of the time those sub-packages will not be updated. 

I see that with `jupyter` sub-packages where people report in their bug reports that they have `jupyter=1.0.0` which is bogus, since `jupyter` is just a virtual package. Instead, they need to report their `jupyter` `notebook` which is at `5.0.7` as of this writing. And I myself got confused between the other of their package versions not once, since they are similar but not the same. But their sub-packages are there for a reason - as they are actually different pieces of software - whereas creating sub-packages just to manage dependencies is not the same.

So my personal preference is to keep a single `fastai` package, and have the conda package fetch all the dependencies, and if you want the refinements then use pip, with refinements suggested by @elyase.

**Comment by elyase** [comment]
To support optional dependencies via pip install, is this just a matter of:

1. changing `setup.py` 
2. go through all imports and make sure they are optional (runtime try except imports) with proper informative Exceptions

or is there something else that has to be considered?

**Comment by stas00** [comment]
Please re-read my first comment - conda is the issue.

**Comment by elyase** [comment]
I mean assuming that we leave out the requirement that "we want fastai to work identically in both", i.e. the optional dependency install would be available via pip as you suggested, is this what needs to be done or is there more to it?

**Comment by stas00** [comment]
First, that would mean that you won't be able to install the default `pip install fastai` anymore, it'll have to become `pip install fastai[all]`, as w/o `[all]` it'll be just base dependencies. And perhaps it's ok.

Second, I haven't looked at the specifics of the code, but I think it'll be more work than just `try: import spacy` - as I suggested it'll most likely take some re-thinking of making each of these functionalities, like `nlp` separate entry points, so that `import fastai` will not attempt to load them at all, but `import fastai.nlp` will need to be called explicitly, and the latter will do all the dep-loading. This will need to be done no matter how we decide to go about the packaging.

But I already shared my thoughts about this and what we need to finish this discussion and to plan action is to have @sgugger and @jph00 to chime in so that we are in agreement.

**Comment by stas00** [comment]
Ok, here is the update - I have discussed this more with @jph00 and here is what we will do for now and you're invited to help with this process.

1. both pypi and conda fastai packages will remain as they are now, since most people won't mind to have it all. But primarily, because it's too complicated for an average user to figure such complexities, and we want simple things to be easy and complicated possible.

2. for the advanced users in order to avoid installing all dependencies, the approach would be to install `fastai` w/o it dependencies, and then installing the dependencies that you need directly:

```
pip install --no-deps fastai
pip install spacy fastprogress numpy ...
```
this will work with conda too:
```
conda install --no-deps fastai
conda install spacy fastprogress numpy ...
```
we will maintain a document that will list dependency groups for each of the domains:

```
fastai.base = fasprogress numpy ...
fastai.text = spacy ...
fastai.vision = torchvision ...
```
so it'll be easy to compile your custom list.

3. we need to make sure that the bare `import fastai` loads without any extra dependencies, beyond it's base list. And the same for each of the domain-specific gateways, e.g. `fastai.text` - so it requires only its extra dependencies.

**Comment by stas00** [comment]
It's fully documented now here:
https://docs.fast.ai/install.html#custom-dependencies

Please experiment and let us know whether this approach is working. I will close this issue for now - please re-open it if you encounter any issues with it.

Thank you.
