### ISSUE TITLE
How to Generating matplotlib graphs without a running X server

### ISSUE THREAD

**Issue by wolfsecond** [fastai/fastai#1365]
the data object of class ImageDataBunch,has a function "show_batch", and "show_batch" seems to use Matplotlib behind to plot any graphic things. And Matplotlib seems to require the $DISPLAY environment variable which means a running X server.
While some web hosting services do not allow a running X server session.
Is there a way to generate graphs using "show_batch" without a running X server?
Thanks for your help

**Comment by CaveSven** [comment]
Did you try this? https://stackoverflow.com/questions/4931376/generating-matplotlib-graphs-without-a-running-x-server

**Comment by wolfsecond** [comment]
> Did you try this? https://stackoverflow.com/questions/4931376/generating-matplotlib-graphs-without-a-running-x-server
in fastai doucmentaion, i failed to find any plt referencte to handle that. all relate fuction are packaged like:
show_batch
plot_lr
so how to do that?

**Comment by CaveSven** [comment]
> so how to do that?

Just type 
`import matplotlib as mpl
mpl.use('Agg')`
at the beginning of your script.

**Comment by sgugger** [comment]
Did it solve your problem? Can I close this issue?

**Comment by nstrodt** [comment]
I also encountered this problem when running fastai code from pure python (rather than Jupyter). From my perspective the cleanest solution would be to allow to pass a matplotlib axis object to all plotting routines. In case None is passed it would fall back to the present behavior. This would give the user the full flexibility to handle the plotting. What do you guys think?

**Comment by kasparlund** [comment]
I have been think that it would be better to move all graphics to a separate graphics module with sub- modules like :
.general confusion matrix etc
.text
.vision
..
that would make it easier to use different graphic libraries. I do admit though that the bulding has a convinving simplicityt to it for first time users 
just a thought?

**Comment by stas00** [comment]
It seems that the linked SO answer was talking about getting an error. I run the following test in a headless environment and received no error (nothing was printed).
```
from fastai.vision import *
path = untar_data(URLs.MNIST_TINY)
data = ImageDataBunch.from_folder(path)
data.show_batch()
```
So there `show_batch` appears not to have a problem in the headless env.

If you want to generate plots rather than display them, perhaps you're expecting from `show_batch` something it wasn't designed to do?

My feeling is that you want another method that specifically creates an image to be saved and then viewed in whatever way you view images. So perhaps something like `render_batch(self, path="/path/to/plot.png", ...)`?

**Comment by nstrodt** [comment]
It's hard for me to decide what was the originally intended functionality. I just think the possibility to pass an axis object to plotting routines would enhance the flexibility of the library.

**Comment by sgugger** [comment]
> It's hard for me to decide what was the originally intended functionality

Well this function is originally designed for people using jupyter notebooks. `show_batch` is already using multiple axes, so I'm not sure it can plot on a given axe. A saved filename seems like a better option. 
In any case, we're happy to consider PRs improving this, but it's not a priority in the development.

**Comment by stas00** [comment]
since there doesn't seem to be any traction here, let's close it for now. If the interests resumes please feel free to reopen.
