### ISSUE TITLE
Proposal to reduce memory usage i LanguageModelLoader by a factor of about 8

### ISSUE THREAD

**Issue by kasparlund** [fastai/fastai#1378]
LanguageModelLoader() is used during training of a language model. Is allocates the entire array of numericalized tokens about 6-8 times thus limiting the the size of the corpus that can be trained drastically

This notebook [https://github.com/kasparlund/nlp/blob/master/ULMFiT%20-%20Wiki%20Training.ipynb]
contains MyLanguageModelLoader() that is an almost streaming oriented version of LanguageModelLoader. It preallocates all required management buffers upfront. It uses less than 5% of the memory of the current LanguageModelLoader and is probably considerably faster.

Apart form the smaller memory usage, the main differences from the current LanguageModelLoader are:
1) data are traverse in batches from start to end, whereas the current version divides the entire set of tokens to "bs" subset and traverses them in parallel. Both uses shuffle and can move forward and backwards so i do not think this change is a disadvantage
2) the randomization of the sequence length s now truely uniform apart for the first iteration in an epoch were i have maintained the longer sequencelength of the current implementation 
3) The epoch in MyLanguageModelLoader uses all tokens by wrapping around and taking tokens form the head/end of the stream when required to fill the last iteration. The current version truncates the end of each "bs" section

Other things that could more easily be done. 
-one could with relative ease make version that always starts a batch on a sentence boundary. ie where a rag starts. The current version starts a batch anywere in a sentence
-Changing the randomization of the sequence length of each iteration is very easy because it does not involve calculations/consideration for the length of the LanguageModelLoader

The purpose of the notebook is to be able to train on the entire corpus of a wikipedia language. This can now be done on the english wikipedia due to the new MyLanguageModelLoader and the the fix in the now closed PR: https://github.com/fastai/fastai/issues/1357. These 2 fixes increases the size of the corpus that i can train on by a factor of about 20 using the notebook

More testing is required but the core ideas are there

**Comment by sgugger** [comment]
I haven't looked at your notebook since I also add an idea to reduce memory usage for huge datasets and wanted to implement mine independently. The final idea is to have such a big dataset stored in some kind of database and only access the texts when necessary. For now, it's still in the items of a `LabelList` but there are no more copies made since texts are accessed when building a batch. As far as I can tell, it has the same functionalities as before.
The downside is that it's a tiny bit slower, but I'm not sure it's really an issue since the GPU is going to be the bottleneck. I'm closing this issue, but please let us know if you find problems with the new implementation, and if you have suggestions to make it even more memory-efficient.

**Comment by kasparlund** [comment]
You new implementation is a very big improvement. I am cleaning up my nlp repository and have further optimisations. 
Should we create a subject in the forum to discus them or how do you prefer to do it ?

**Comment by sgugger** [comment]
A topic on the forum would be best for this, thanks!
