### ISSUE TITLE
Accuracy reduces on reloading model after closing and relaunching the vm/instance

### ISSUE THREAD

**Issue by rwikdutta** [fastai/fastai#1388]
Whenever there is a dataset which has integers as labels, the FastAI library doesn't handle the dataset properly when we try to reload previously trained weights for the same set of data ( validation and training datapoints doesn't change between the two sessions ) . As a result, the metrics drop ( see section 2 in the attached notebook ) .

To reproduce the issue, see Section 1 and Section 2 of the attached notebook.

As a control, I have shown section 3 and section 4 in the notebook where the accuracy doesn't drop even after resetting the vm/restarting the instance. This happens when the same dataset is used with the same datapoints for training and validation, but the class labels are strings and not integers.

Find the attached notebook here: https://colab.research.google.com/drive/1EElj-oyrF3a0yLPLTw-f74hE5MBE7OXN

**Comment by sgugger** [comment]
Be careful, you forgot to normalize in your section 1 (you also save the file dataset.csv not in path, but that doesn't change the results if I save it properly). Since you normalize your data in section 2, the results are of course very different. When I add normalization in section 1 (or remove it in section 2), the bug disappears.
