### ISSUE TITLE
train_ds image is much smaller than valid_ds image

### ISSUE THREAD

**Issue by PsidomPC** [fastai/fastai#1413]
**Describe the bug**

Was playing around with fastai with standford car data set, but it seems the image size in train_ds is very small compared to valid_ds. Should they be the same? Or I am assuming something wrong here?

**To Reproduce**

**Expected behavior**

The train_ds image size should have be the same as valid_ds;

**Screenshots**

![ImageDataBunch](https://s3.amazonaws.com/learn-fastai-share/fastai.PNG)

**Additional context**

**Comment by sgugger** [comment]
You're putting in transforms `rand_pad(2,28)` (so padding of 2 then resize to 28x28 for the training set, crop center). Since this only one set of transforms, there is no validation transforms so you get the original image.
This is consistent behavior from the library, not a bug. You should put other transforms for `ds_tfms`.
