### ISSUE TITLE
TypeError: on_epoch_end() missing 1 required positional argument: 'smooth_loss'

### ISSUE THREAD

**Issue by daleevans** [fastai/fastai#1499]
**Describe the bug**
When trying to train a toy network with small training using a TextDataBunch (less than 32 samples, I think) the training loop crashes.

However, I can still train a network with a very small sample set of only 4 items if I manually construct the databunch in other ways.

**Provide your installation details**

I'm using the very latest from the github repo, commit 94347d87acc42100841aa35c6b586850d75bbbf6

```
=== Software === 
python       : 3.6.6
fastai       : 1.0.40.dev0
fastprogress : 0.1.18
torch        : 1.0.0
torch cuda   : None / is **Not available** 

=== Hardware === 
No GPUs available 

=== Environment === 
platform     : Linux-3.16.0-4-amd64-x86_64-with-debian-9.5
distro       : #1 SMP Debian 3.16.51-3 (2017-12-13)
conda env    : Unknown
python       : /usr/local/bin/python
sys.path     : /opt/project
/usr/local/lib/python36.zip
/usr/local/lib/python3.6
/usr/local/lib/python3.6/lib-dynload

/usr/local/lib/python3.6/site-packages
/opt/project/jupyter/fastai
/usr/local/lib/python3.6/site-packages/IPython/extensions
/home/django/.ipython
no supported gpus found on this system
``````
or via your shell:
```

**To Reproduce**

This gist should replicate the issue.

https://gist.github.com/daleevans/fd872a5d5bf7bd947545d57d5b2bc226

Note, to make the gist work, add this:

raw = raw + raw
raw = raw + raw
raw = raw + raw

to increase the size of the dataframe to 32 samples.

**Expected behavior**
It should train the network instead of crashing.

**Comment by holmesal** [comment]
@daleevans I ran into this as well - in my case, it was because I had less than a single batch's worth of data. Decreasing my batch size **or** increasing the amount of data fixed the issue.

FWIW, two tweaks that would have helped me chase this down faster:

### 1. a better small-batch-size error message
I was getting a warning:
> Your training dataloader is empty, you have only 63 items in your training set

I'm a beginner, so it took me a bit to figure out that the *reason* my 63 items weren't making it into my data loader was because of my batch size (64). Seems like this warning could be improved by maybe just including the current batch size.

### 2. a better crash location
The crash that occurs is a missing positional argument, which IIUC happens because `smooth_loss` isn't present on `CallbackHandler.state_dict` when `basic_train.Recorder.on_epoch_end` is called. I'm not totally clear on why a too-small batch size causes this, but it seems like there are probably better places for this error to surface than the epoch end callback!

**Comment by sgugger** [comment]
Put an assert at the beginning of fit to catch that empty dataloader and throw a clear error message. Also changes the warning message in `DataBunch` to make it clearer.
