### ISSUE TITLE
How to implement seq2seq with fastai1.0?  Such as machine translation.

### ISSUE THREAD

**Issue by illcat** [fastai/fastai#1542]
Is there an API like TextLMDataBunch?
Thank you!

**Comment by sgugger** [comment]
Not yet. In the meantime a few people have started discussing it on the [forum](https://forums.fast.ai/), you should check there.
I'm closing this issue since we know it's a desired feature and it's on our TODO before the second part of the course, but it won't come before end of February/beginning of March.
