### ISSUE TITLE
no_split error

### ISSUE THREAD

**Issue by benwu232** [fastai/fastai#1557]
When I called no_split() first, I found len(train_dl) is one less than the right number. It seems the remained data less than one batch is not counted.

**Comment by sgugger** [comment]
The training dataloader is always loaded with `drop_last=True` to avoid having a last batch with few elements (a size 1 will throw an error if you have BathNorm layers and in general a too small size will be unstable for training). That may be the reason you see one less than the right reason.
Otherwise, please provide us a minimal code that reproduce the bug.
