### ISSUE TITLE
I want to validate on another set, But 

### ISSUE THREAD

**Issue by illcat** [fastai/fastai#1559]
The same data tests were used to test the "validate" function only.
But the result is not right.
![image](https://user-images.githubusercontent.com/40688514/52167796-c315be00-275b-11e9-9978-605e408c8440.png)

**Comment by illcat** [comment]
The correct result is the same score.  
【0.05， 0.67， 0.59， 0.50】Instead of 【0.12， 0.15， 0.13， 0.01】

**Comment by illcat** [comment]
Changing learn.data does not evaluate other data sets, and there is an error!

**Comment by sgugger** [comment]
You didn't specify a vocab when creating your second `DataBunch` so it didn't use the same one as you were using before. This is probably why you get different results (also I don't know why you say it doesn't evaluate on another dataset, it is clearly doing so since it's not giving the same results).
You should add `vocab = old_data.vocab`.

**Comment by illcat** [comment]
The problem has been solved.
Thank you for your kind reply!
