### ISSUE TITLE
ImageClassifierData.from_paths cannot be called without transforms

### ISSUE THREAD

**Issue by radekosmulski** [fastai/fastai#163]
![download](https://user-images.githubusercontent.com/2444926/36350431-e2b4733c-1497-11e8-8a3a-78c589afd9cd.png)

This is raised because FilesDataset expects to be passed `transform` that responds to `sz`

```python
class FilesDataset(BaseDataset):
    def __init__(self, fnames, transform, path):
        self.path,self.fnames = path,fnames
        super().__init__(transform)
    def get_n(self): return len(self.y)
    def get_sz(self): return self.transform.sz
```

I do not know what would be the correct way to fix this. Assuming images of varying sizes can live in referenced directories this gets tricky. I am also not sure if anything else uses this or if it is just a convenience method for the user.

(BTW I can train the model ok with just setting the body of `get_sz` to `pass`)

**Comment by kkbrandt** [comment]
I assume you've read the discussion about this at http://forums.fast.ai/t/fastai-dataset-imageclassifierdata-from-paths-without-transformations/9778 ?
This seems like a reasonable requirement to me, since the user will need to specify the size of the images they want.
What behavior would you expect from passing no transform?
This seems to cause quite a bit of confusion, and at the very least we should have parameter checking here to display a better error message

**Comment by radekosmulski** [comment]
I was not aware of the conversation - thank you for pointing me to it.

On one hand I fully understand the argument for making the transforms necessary and this might be the way to go on this. Should clear some of the confusion (leaning towards this solution).

Wanted to say that on the other hand I am tempted by giving users the extra flexibility of just running images straight from a directory, but the more I think about it the less convinced I am that this is the way to go - especially as it might make the code unnecessarily complex.
