### ISSUE TITLE
jupyter notebook takes quite long before training

### ISSUE THREAD

**Issue by Babuschka** [fastai/fastai#2203]
**Describe the bug**

Before training, the notebook seems to do nothing at all for over one minute, even for this little task. After finally starting the training, the progress bar fills within two seconds. The Task manager shows only slim peaks for the CPU and the Cuda working processes at the time while the progress bars are filling up

**To Reproduce**
```
from fastai.vision import *

path = untar_data(URLs.MNIST_SAMPLE)
data = ImageDataBunch.from_folder(path)

model = simple_cnn( (3, 16, 16, 2) )
learn = Learner(data, model)

learn.fit(1)
```

**Expected behavior**

Since it is a very small example, I expected a similar time as in the FastAI docs, where the training lasted only 3 seconds.

**Additional context**
I'm using FastAI on Windows 10 with a GeForce 1080 Ti

Did I do something wrong, or is this even strange?

**Comment by sgugger** [comment]
This runs normally for me. I think it's link to PyTorch DataLoader being slow on Windows ([see here](https://github.com/pytorch/pytorch/issues/12831) for the issue filed on PyTorch). In general you can't have fast DataLoader in jupyter notebook on windows because of some issues linked to multiprocessing, from my understanding.

Closing because this isn't linked to fastai and there is little we can do about it on our side.
