### ISSUE TITLE
access train_idx or valid_idx after split_by_rand_pct

### ISSUE THREAD

**Issue by nkierdem** [fastai/fastai#2232]
This is not a bug, but more of a question regarding the implementation.

When I use `split_by_rand_pct`, it creates training and validation datasets randomly. But after then I do not have any knowledge about which data is selected for training or validation. It would be good to be able to access to `train_idx` and `valid_idx` even after splitting data. Is it a good idea to preserve  as attributes? If there is another way please let me know.

**Comment by sgugger** [comment]
Those aren't saved, but if reproducibility is your issue, you can pass a `seed` for the random split to be the same.
Otherwise, you can access the selected items in `data.train_ds.x.items` and `data.valid_ds.x.items` once at the `DataBunch` stage.

In general, we use the [forum](https://forums.fast.ai/) for questions around the library and keep issues for known bugs only.

**Comment by nkierdem** [comment]
`data.train_ds.x.items` is an array of numbers from 0 until len(train_ds.x) for me. I am not sure what it would be useful for. But I have found what is useful for me: `data.train_ds.x.inner_df`. Thank you for your help.
