### ISSUE TITLE
Confused by the plot_confusion_matrix output 

### ISSUE THREAD

**Issue by kleinash** [fastai/fastai#2263]
**Describe the bug**
interp.plot_confusion_matrix(figsize=(12,12), dpi=60) produces a confusion matrix that does not show the diagnol values for when the prediction is correct. 

**Provide your installation details**

**To Reproduce**

```
path = '/path/to/folders/of/images'
src = ImageList.from_folder(path).split_subsets(train_size = train_size, valid_size = valid_size, seed = model).label_from_folder() # the label is a string
data = src.transform(tfms=None, size=size, resize_method=ResizeMethod.SQUISH).databunch(bs=batch_size, num_workers=4).normalize(imagenet_stats)
learn = learn.load('/path/to/folders/of/training/images/models/tmp')
learn.validate(data_test.valid_dl)
interp = ClassificationInterpretation.from_learner(learn)
interp.plot_confusion_matrix(figsize=(12,12), dpi=60)
```

**Expected behavior**
I expect a confusion matrix that has the darkest (most) blocks along the diagonal

**Screenshots**
This is what I am getting:
![image](https://user-images.githubusercontent.com/2494123/62485993-22e13600-b78c-11e9-9864-842f2ff4db88.png)

**Comment by kleinash** [comment]
The model performs at 91%

**Comment by sgugger** [comment]
I'm afraid there is little anyone can do to help on this since we don't have your data or your model. Plus part of your code (like the Learner creation) is missing. On the examples I have, the confusion matrix is looking correct.
If you have a more minimal reproducible example where the confusion matrix is clearly wrong, and that we can reproduce, I'll be happy to dig into it and find a fix, but I can't fix something I can't reproduce.
