### ISSUE TITLE
Ability to fetch Image Ids from databunch objects

### ISSUE THREAD

**Issue by jaideep11061982** [fastai/fastai#2297]
**Describe the bug**

This is not a bug but an enhancement request,i have seen queries in forum regard to fetching of image ids of dataset from databunch . When a databunch gets built original indices of  input training set  in train Dataframe  gets lost ,when we do learn.show_Results() we only see image object ,gt and ap. It would have been a very handy thing if there was an image id  also visible when we do show_results.
Similarly when we fetch top_losses  we see the indices of image in databunch image objects but not the indices from  source dataframe. So if the top losses can instead return the indices from original dataframe  it would make things very easier for every one.

**Provide your installation details**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
That's not possible because once things are batched in a PyTorch dataloader, we don't get the indices they come back from, only the tensors. v2 will have a more general dataloader that we rewrote, which might make things like this possible, but this won't be added in v1.

Closing the issue since we keep those for standing bugs only, please add this to the thread in the [forum](https://forums.fast.ai) dedicated to new features.
