### ISSUE TITLE
Load pickle data (from databunch) in colab

### ISSUE THREAD

**Issue by yonatanbitton** [fastai/fastai#2340]
Hello. 
I have data for LM that was created like that: 

`wiki_data = TextList.from_folder(path).split_by_folder(train='train', valid='valid').label_for_lm(ignore_empty=True).databunch(bs=24)`

I've saved it in Windows: 
`wiki_data.save('wiki_data.pkl')`

Now I want to train a model on it in colab. 

So I've mounted the drive in colab, and uploaded the pickle file to that location. 
```
from google.colab import drive
drive.mount('/content/drive', force_remount=True)
```

When trying to load the data, I've tried two paths: 
```
path1 = '/content/drive/My Drive/Colab Notebooks/data'
path2 = Path('/content/drive/My Drive/Colab Notebooks/data')
```

And then 
`wiki_data = load_data(path1, 'wiki_data.pkl', bs=24)
`
`wiki_data = load_data(path2, 'wiki_data.pkl', bs=24)
`

But I get the same error: 
`NotImplementedError: cannot instantiate 'WindowsPath' on your system
`

How can I solve it ? 

I just want to train the LM in the colab in order to have faster GPU. Thanks.

**Comment by sgugger** [comment]
Yes, the problem comes from the pathlib library, Path objects are not compatible between Windows and Linux once serialized. We have a workaround for inference in `Learner.export` and `load_learner` but for data objects, there is no compatibility between saving on one OS and loading on another one. 
This is a known issue that will be addressed in v2, but it's too much work for v1.
