### ISSUE TITLE
Docs as PR's

### ISSUE THREAD

**Issue by blakewest** [fastai/fastai#236]
Hi @jph00 ,
Not sure if this is the best place to raise this, but I'm curious if you're welcome to PR's that add documentation to methods, classes, etc. If so, anything to know about how you prefer your docs?
I ask because while using the notebooks, I often find myself looking at some method or class, and typing "Shift + Tab" in the notebook, only to find no doc string, which is frustrating. 
My plan would be to follow the style of the docs that do exist.

**Comment by jph00** [comment]
We could have a better discussion on the forum, but the short answer is
yes, I'd love to have more docs. My preference (which we haven't
implemented anywhere yet) is to have a more fleshed-out doc in a
separate doc/ folder (which we'd then host somewhere) and a short
summary docstring with a link to the full docs for that symbol.

If you don't have time to help set something like that up, adding longer
docstrings would still be very helpful, since we can always paste them
into the full docs later if we set that up.

**Comment by blakewest** [comment]
@jph00 sounds good. Yeah I hate having the code base littered with giant comments just for docs. We had that at my job, but it's pretty distracting for developers, so we moved away from it in favor of using [Swagger](https://swagger.io/docs/
), which is in a separate file, and then gets hosted externally. Swagger is designed for web API's though. I'll do a bit of sleuthing and see what's out there.

**Comment by jph00** [comment]
Thanks! I'll close this issue whilst you're sleuthing - feel free to open a new one if required.
