### ISSUE TITLE
release check against v1.3.0

### ISSUE THREAD

**Issue by soumith** [fastai/fastai#2365]
Hi there,

The release branch for PyTorch v1.3.0 is finalized: https://github.com/pytorch/pytorch/tree/v1.3.0
This is a "heads-up" issue to test for incompatibilities and be ready for the next version.
The version is slated to go live on 10th October (Thursday).

We've added fastai to our integration testing with nightlies, but release branch testing is currently manual (we are working on automating it).
[fastai test "test_purge" is failing on pytorch nightlies as an fyi](https://app.circleci.com/jobs/github/pytorch/builder/5485/parallel-runs/0/steps/0-121), but currently we have no idea if that's true for the release branch, I'll get to it between now and Wednesday.

PyTorch maintainers

**Comment by sgugger** [comment]
Oh thanks for warning us and including fastai on your integration testing. 
Not sure the issue here is related to anything in PyTorch since the normal `learn.purge` before passes and this is a test of a failure if we operate on a non-writable dir. Maybe there is a change in the error message. Let us know if it stays in the release branch, I'll try to reproduce on the nightlies in the meantime.

**Comment by sgugger** [comment]
I can't reproduce the failure with the nightlies. My best guess would be that something fails with setting up a directory without writing permissions in PyTorch integration testing. In any case this is a test we don't really need, the function in itself is already thoroughly tested, so we removed it.

Let me know if the tests pass now on your side @soumith and I'll close this issue.

**Comment by soumith** [comment]
did you get a chance to test v1.3.0 against fastai ? 1.3.0 was branched off of master branch on at end of september.

**Comment by sgugger** [comment]
Is there a build of v1.3.0 like the nightlies somewhere easily accessible?
