### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by millermuttu** [fastai/fastai#2372]
File "setup.py", line 59
    print(f"Error: Invalid group name(s): {', '.join(invalid_groups)}")

**Comment by sgugger** [comment]
Please follow the template when filing an issue. We can't help you if we don't understand what your problem is.

**Comment by Davies-Owen** [comment]
@sgugger I'm encountering an issue at the same line when trying to install fastai via pip3 on a Ubuntu 16.04 Docker container. 
The shebang at the top of setup.py specifies it's intended to be interpreted by Python 2.7, but `print(f"Error: Invalid group name(s): {', '.join(invalid_groups)}")` is only valid syntax in Python 3. During the installation process, setup.py is run with Python 2.7, producing a syntax error rather than the useful error message that is supposed to be printed here.
