### ISSUE TITLE
Updates for changes in PyTorch master Tensor subclassing behavior

### ISSUE THREAD

**Issue by ezyang** [fastai/fastai#2616]
Hey peeps,

We're going to be landing https://github.com/pytorch/pytorch/pull/37091 soon to master, which changes the default behavior of subclasses of Tensor. Previously, if you ran an operation on a tensor subclass, you'd get out a Tensor, rather than the subclass. With this PR, the default behavior changes, and you'll get back the subclass in the end.

I heard that fastai uses `make_subclass` on Tensor, which is why I figured y'all might be affected. (Though I'm not exactly sure how it is being used.) Let me know if you have any questions.

cc @hameerabbasi

**Comment by jph00** [comment]
Thanks this is great to know, @ezyang. Yes we rely on it heavily, in order to monkey-patch in the exact change that that PR makes. Can you please let us know when a nightly is available, so we can test it? It'll be terrific to remove our monkey-patching.

Also, `_make_subclass` previously deleted the grad history and the `requires_grad` attr. Has that been fixed too?

**Comment by hameerabbasi** [comment]
@jph00 Can you possibly test `as_subclass`, which uses `alias`, to see if it has these shortcomings?

**Comment by jph00** [comment]
Yes that fixes that problem.

However, it seems to lose `__dict__`, so any attrs added are removed. Is that intentional? Is there a workaround?

**Comment by hameerabbasi** [comment]
That was intentional. However, one can use `__torch_function__` for exactly that purpose.

**Comment by jph00** [comment]
Here's an example:

```
t = tensor([1.0])
t.requires_grad = True
o = tensor([1.0])
z1 = t+o
setattr(z1,'_meta',1)

class TensorBase(Tensor):
    def __repr__(self):
        return re.sub('tensor', self.__class__.__name__, super().__repr__())

z2 = z1.as_subclass(TensorBase)
z2,z2.requires_grad, z1,z1.requires_grad
```

Result is as expected:

```
(TensorBase([2.], grad_fn=<AliasBackward>),
 True,
 tensor([2.], grad_fn=<AddBackward0>),
 True)
```

But `z2._meta` is missing.

**Comment by jph00** [comment]
How do I use `__torch_function__` to subclass `Tensor` and keep `__dict__` ?

**Comment by jph00** [comment]
Just looking at the helpful `ScalarTensor` example of `__torch_function__` in the docs, and whilst that is very cool functionality, I don't think it will handle what we need, which really is sub-classing. We'd have to heavily rewrite fastai2's foundations otherwise.

I can just patch pytorch to copy over `__dict__` in `as_subclass`, I guess. I'll try that now.

**Comment by hameerabbasi** [comment]
Here's the RFC, with a bunch of examples: https://github.com/pytorch/rfcs/blob/cb335a0cbf11a8a9433f7119a228fd79c963d8a1/RFC-0001-torch-function-for-methods.md

**Comment by jph00** [comment]
Thanks @hameerabbasi . I've read that before - but just took another look thru to re-check. There doesn't seem to be any suggestion there of a way to subclass Tensor and retain `__dict__`; apologies if I'm missing it, however.

**Comment by hameerabbasi** [comment]
Could you post, in an ideal world, a MVE of what you'd like to "just work"?

**Comment by jph00** [comment]
Absolutely! :) The MVE is the code here: https://github.com/fastai/fastai/issues/2616#issuecomment-665838264

Having said that, don't worry about it too much, because I've tried patching it now and it's working fine. :)

**Comment by jph00** [comment]
Closing this now since our workaround in fastai2 has been working fine for a while now so all's well.
