### ISSUE TITLE
show_batch not working with korean labels

### ISSUE THREAD

**Issue by foobar8675** [fastai/fastai#2692]
Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES 

**Describe the bug**
My labels are in korean, so when I call `show_batch` the labels do not show. I've tried resetting the global fonts for matplotlib but it has not worked. I also know you can pass a `fontproperties` to various plt methods, but I don't see a way to access that object in fastai.

<img width="630" alt="Screen Shot 2020-08-25 at 10 43 43 PM" src="https://user-images.githubusercontent.com/1685700/91249311-7ada3a00-e70b-11ea-822f-15db5dd60009.png">

here is a link to the colab, which closely resembles lesson 6
https://colab.research.google.com/drive/1z7zi9Dc9xP8rBhPHccFWi5J2YUsQuJoM?usp=sharing

**To Reproduce**
see colab 

**Expected behavior**

**Error with full stack trace**

Place between these lines with triple backticks:

```
```

**Additional context**

**Comment by tyoc213** [comment]
@foobar8675  https://storage.googleapis.com/mclabs-ocr-dataset/hangul.zip doesnt exist?

**Comment by foobar8675** [comment]
@tyoc213 sorry about that. just fixed and should work now.

**Comment by tyoc213** [comment]
![image](https://user-images.githubusercontent.com/506234/93694134-dc54b500-facd-11ea-9e5e-71281b8540b1.png)


Try this https://buomsoo-kim.github.io/colab/2018/04/27/Using-External-fonts-in-colab.md/ or better https://github.com/tensorflow/tensorflow/issues/42780#issuecomment-617267129

In collab it seems that is a know issue for the font they use. (Dont know which one is)

Tried and got this (because locally also doesnt show)

![image](https://user-images.githubusercontent.com/506234/93694306-a0baea80-facf-11ea-80ac-e1b377c881fe.png)

**Comment by foobar8675** [comment]
That is awesome. Thanks!
