### ISSUE TITLE
Tutorial – Transformers fastai.text.all import and hardware requirements

### ISSUE THREAD

**Issue by tomacai** [fastai/fastai#2725]
I am running the Tutorial – Transformers colab notebook but on fastai import I get the error 
```
from fastai.text.all import *
ModuleNotFoundError: No module named 'fastai.text.all' 
!pip freeze | grep fastai
fastai==1.0.61 
```

With fastai2.text.all import * 
it is fine (after installation of fastai2). So probably an errata on the tutorial.

However the notebook bombs out on memory requirements on a Tesla P100-PCIE-16GB in Azure!
`CUDA out of memory. Tried to allocate 786.00 MiB (GPU 0; 15.90 GiB total capacity; 14.30 GiB already allocated; 743.75 MiB free; 14.40 GiB reserved in total by PyTorch)
`
What hardware did you run this on?

**Comment by muellerzr** [comment]
First: you need to upgrade via `pip install fastai --upgrade`

Second: Colab (not sure if you're doing the free version or the paid)'s GPU's are much smaller than what Jeremy runs on, so lower the batch size.

Finally, this is a question better suited for forums.fast.ai rather than opening a github issue
