### ISSUE TITLE
AttributeError: Can't get attribute 'FlattenedLoss'

### ISSUE THREAD

**Issue by MUHAMMAD0KASHIF** [fastai/fastai#2748]
I have following installed on my ubuntu 18
fastai                        2.0.6              
torch                         1.6.0+cpu          
torchvision                   0.7.0+cpu 
I am trying to load my export.pkl file in following way but it is not being loaded and getting following exception:
>>> from fastai import basics
>>> basics.load_learner('export.pkl')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/fastai/learner.py", line 539, in load_learner
    res = torch.load(fname, map_location='cpu' if cpu else None)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 584, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 842, in _load
    result = unpickler.load()
AttributeError: Can't get attribute 'FlattenedLoss' on <module 'fastai.layers' from '/usr/local/lib/python3.6/dist-packages/fastai/layers.py'>
>>>

**Comment by KushajveerSingh** [comment]
I think there was an upgrade in which `FlattenedLoss` got changed to `BaseLoss`.

**Comment by danvelev** [comment]
I had the same error and managed to fix it by updating my library of fastai to be matching the version of fastai where I load the file.
E.g. code where I was exporting the model was running 1.0.60, code loading the model was running 2.0.10. Hence by making sure those version are matching you will avoid this error (seems like there are quite some difference between fastai v1.0.* and fastai v2.0.*)
(make sure to check the versions in python itself as well, not just with `pip list` -> e.g. `import fastai; fastai.__version__`) I was checking installed packages in pip, without realising that I needed to restart my kernel after up-/downgrading for instance 😅 🤦‍♂️

NOTE: if you have the same case as me, would recommend you to downgrade the version on the code where you load the model, since upgrading the other one would deprecate your code and give you more errors on the functions you are using. ;) 

Hope this helps and saves you some time debugging 🙌

**Comment by MUHAMMAD0KASHIF** [comment]
thank you danvelev,  the issue was due to different version. I trained model on colab but while deploying on production the version I installed using pip it was latest so by downgrading I manged it.
Thank you
