### ISSUE TITLE
ADULT_SAMPLE does not run

### ISSUE THREAD

**Issue by yrzhanov** [fastai/fastai#2788]
Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES

**Describe the bug**
In 01_intro notebook ADULT_SAMPLE example does not run. Does not report any failure - just jumps to the next cell.

**Comment by yrzhanov** [comment]
NB: The next ML_SAMPLE right after it runs fine.

**Comment by asvcode** [comment]
If you are referring to this cell:
```
from fastai.tabular.all import *
path = untar_data(URLs.ADULT_SAMPLE)

dls = TabularDataLoaders.from_csv(path/'adult.csv', path=path, y_names="salary",
    cat_names = ['workclass', 'education', 'marital-status', 'occupation',
                 'relationship', 'race'],
    cont_names = ['age', 'fnlwgt', 'education-num'],
    procs = [Categorify, FillMissing, Normalize])

learn = tabular_learner(dls, metrics=accuracy)
```
Then it is behaving as expected.  There should be no output.  The output will generate when you run the very next cell:

`learn.fit_one_cycle(3)`

The reason the `ML_SAMPLE` cell has an output is because that cell has `learn.fine_tune(10)`  in the cell so as expected you get an output

if this resolves the issues please close this issue thanks

**Comment by yrzhanov** [comment]
Got it. Maybe it's worth adding some feedback, like "Now run the next cell"?
