### ISSUE TITLE
get_preds fails when passed a dataloader where the batchsize does not evenly divide the number of items

### ISSUE THREAD

**Issue by adamfarquhar** [fastai/fastai#2874]
Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES

**Describe the bug**
See the forum item: https://forums.fast.ai/t/learn-get-preds-batch-size-and-number-of-items-mismatch-error/79649

If get_preds receives a dataloader where batchsize does not evenly divide the number of items, then it fails with an error:
IndexError: index 98 is out of bounds for dimension 0 with size 96

**To Reproduce**

Call get_preds with a dataloader containing a number of items that is not an integer multiple of the batchsize.

**Expected behavior**
Get_preds should return predictions for all if the items in the dataloader.

**Error with full stack trace**
See the previously reported item on the forum. 
```
```

**Additional context**

**Comment by dreamflasher** [comment]
I can reproduce the bug and would appreciate a fix.

**Comment by dreamflasher** [comment]
The solution is to make predictions in the following way:
```
probs, _ = learn.get_preds(dl=learn.dls.test_dl(files, drop_last=False))
```
Somewhere drop_last defaults to True, which should be changed.

**Comment by muellerzr** [comment]
@dreamflasher @adamfarquhar the issue is you're trying to pass in a *set* of `DataLoaders`, where `get_preds` can only get inference on **one** `DataLoader` at a time. @dreamflasher solution is correct because it is the proper way to use the inference API.

**Comment by jph00** [comment]
@adamfarquhar FYI in the future, in the "To reproduce" section please provide complete code to reproduce the problem from scratch, rather than just a general description.

**Comment by dreamflasher** [comment]
@jph00 @muellerzr Why is the drop_last necessary, though? Shouldn't that default to false for a test_dl?

**Comment by muellerzr** [comment]
It always is. The issue had nothing to do with the DataLoader itself moreso
the fact they were passing in both DataLoaders to get_preds. If you can
create a reproducible example of test_dl dropping the last batch please
open an issue however all test_dl’s should not drop the last batch since
they’re generated based on the validation DataLoader.

**Comment by kevinbird15** [comment]
I looked into this and I think the *problem* is how you are creating your test_dl.  I think the preferred method of getting a test_dl to put into `preds, ground_truth = learn.get_preds(dl=test_dls.train)` would be https://docs.fast.ai/data.core.html#DataLoaders.test_dl and here is an example using your example: 

```python
test_dl = learn.dls.test_dl(test_df)
preds, ground_truth = learn.get_preds(dl=test_dl)
test_dl.drop_last #This now outputs False by default
```

I think this should still be considered a bug though because if I pass the training set in using ds_idx=0, it runs fine because get_preds specifically creates a new dl with drop_last=False: 
`if dl is None: dl = self.dls[ds_idx].new(shuffle=False, drop_last=False)`

I think the question is whether we want to change a dl that somebody specifically passes in to get_preds if somebody passes a dl that is *not* None.  I can think of a few different ways to handle it.  Probably the easiest would just be to do a dl check and say 

```
if dl.drop_last: dl = dl.new(shuffle=False, drop_last=False)
```

I've tested this and it does work so I'm adding it as a suggested fix in new incoming PR
