### ISSUE TITLE
Fast ai Siamese tutorial:  Random augmentation are symmetric on pairs

### ISSUE THREAD

**Issue by kessido** [fastai/fastai#2898]
The tutorial provided show how to pair images, and that the transformation are applied on them, be it because they are made of pair\because they are inheriting from fastuple, etc.
But because of the design of transformation in fastai, few problem arise:
1. RandomResizeCrop does not work anymore: code for "before call" only implemented for b[0] == image, and does not expect b[0] == tuple of images.
2. augmentations are applied in similar fasion to both images, introducing a new dependent variable to the training which is not presented in real world.

Not sure there is an easy fix, for my case I created a pipe that contain a combination of single image pipeline, and change the get_idxs function to return ordered element, and then grouped them later on in the network (quite the hack, not really to my liking I must say.)

would love hearing your opnions :)
Ido

**Comment by marii-moe** [comment]
I haven't taken a look at this myself, but this may be related to RandomResizeCrop being a batch transform, instead of applying the transform differently to each item in a batch. To whoever takes this up it maybe useful information to make sure RandomResizeCrop still works on an entire batch instead of individual items.

**Comment by jph00** [comment]
Best to ask on the forums for help.
