### ISSUE TITLE
learn.TTA with tfm_y=TfmType.CLASS bug

### ISSUE THREAD

**Issue by fredguth** [fastai/fastai#646]
`learn.TTA` doesn't seem to comprise the segmentation case. 

If I do `probs = learn.TTA(n_aug=2)`, probs shape is something like (3, num_images, img_sz, image_sz, channels).

probs[0] is the segmentation with image without augmentation, probs[1] is the segmentation of the image with first augmentation applied, probs[2] is the segmentation with 2nd segmentation applied.
One cannot average these results, as each augmentation transforms the output accordingly.

See example here: https://www.evernote.com/l/AZScajJNXAdLIpp66Qg_FkctMkeOK3kFY3EB/image.png
(I also posted at http://forums.fast.ai/t/lesson-14-segmentation/19530/5)

Unless we know how to inverse the augmentation transformation in the result, learn.TTA is useless.

My suggestion is that, knowing that the data has ` tfm_y=TfmType.CLASS`, the learn.TTA code should inverse the augmentation transform to probs[1] and probs [2] (in my example).

**Comment by sgugger** [comment]
Good point.
We are in the process of rewriting the library entirely with Jeremy, so we will keep this in mind for fastai_v1. In the meantime though, the adjustments we make to this library are minimal (by lack of time). If you can see how to make a PR to correct this, we'll gladly accept it, otherwise it will have to wait for v1.

**Comment by fredguth** [comment]
No problem.  I would be glad to help with this.
Do you know if fastai keeps track of what transformation was applied?  
How is the best way to contribute? PR to fastai repo or fastai_v1? Is fastai_v1 stable?

**Comment by fredguth** [comment]
Ok, I will check.

**Comment by MichaelSluydts** [comment]
Hey,

Apologies for reopening this if there should already be changes made in FastAI 1. Recently, I was facing the same problem though and was not entirely sure what the best way of tackling it is. 

@sgugger, from how I interpret your answer it would seem to suggest the images are not being transformed in the TTA. The problem I think both the topic opener and myself share I think is that you indeed the function returns the transformed images and perhaps you can score them individually. What you cannot do however is do the inverse transformation. The latter would be necessary if, in the segmentation case you want to average the pixel-wise predictions of each case.

If I have time I could also try having a look at it. Could you give some hints perhaps as to whether the inverse transformation is somehow easily accessible in FastAI? Thanks!

**Comment by sgugger** [comment]
I hadn't fully thought about this issue at first, but as you say, the key point is that we need the inverse transformation of what was applied to the image. This isn't implemented in fastai and would require a profound change in the transforms.py module, which is why this functionality won't be developed for fastai, only for fastai_v1.
I'm keeping this closed for that reason.
