### ISSUE TITLE
Is learn.wd supposed to change/be set with learn.fit_one_cycle and/or learn.lr_find?

### ISSUE THREAD

**Issue by jmhsi** [fastai/fastai#893]
How am I supposed to check that the correct wd is being used when calling learn.lr_find or learn.fit_one_cycle? 
When I call get_tabular_learner, if I don't specify a wd, it defaults to 0.01. Was this intended?

Steps:

1) I create a tabular learner without any wd specified; print(learn.wd) prints .01
2) I create a tabular learner with wd=5
3) I set wd=1e-4 and use it in my call to learn.fit_one_cycle()
4) learn.wd is still 5
5) I set learn.wd = wd and verify it is now 1e-4

![screen shot 2018-10-12 at 1 37 28 pm](https://user-images.githubusercontent.com/12853718/46893000-42d1f280-ce24-11e8-8183-b0c7d511babd.png)

![screen shot 2018-10-12 at 1 37 41 pm](https://user-images.githubusercontent.com/12853718/46893012-4f564b00-ce24-11e8-9f65-1fd082708690.png)

**Comment by sgugger** [comment]
I don't see where the bug is:
- learner has a default wd of 1e-2 if you don't specify anything
- if you specify learner.wd = something, it changes it
- in a fit or fit_one_cycle function, if you specify a wd, it overrides learn.wd, but learn.wd keeps its value.

Please note that there is a [forum](http://forums.fast.ai/) to ask those questions, and that many more would benefit from the answers there than here ;)
