### ISSUE TITLE
Examples in examples folder not showing

### ISSUE THREAD

**Issue by discdiver** [fastai/fastai#911]
**Describe the bug**
Example jupyter notebook files in examples folder not showing.

**To Reproduce**
Go to [https://github.com/fastai/fastai/blob/master/examples/collab.ipynb](https://github.com/fastai/fastai/blob/master/examples/collab.ipynb) for example.

**Expected behavior**
Jupyter notebooks with examples were visible a few days ago. It looks like someone updated the files recently.

**Screenshots**
![screen shot 2018-10-17 at 2 01 44 pm](https://user-images.githubusercontent.com/7703961/47106748-72fb0600-d215-11e8-9323-415c319e61ec.png)

**Comment by stas00** [comment]
It looks like a github issue. I confirm that I get the same. But if I try a version from 2 weeks ago [1] it doesn't render either, so it's not the file, but github - I suggest to report this to support. Thank you.

[1] https://github.com/fastai/fastai/blob/bc84f8fd4c42a6423a6f814c2b6129b43930c8c3/examples/cifar.ipynb

**Comment by stas00** [comment]
Also found this issue from a year ago, https://github.com/jupyter/notebook/issues/3035, and someone suggested the size could be a problem, but as I tested going back a few weeks none of them renders.

You can experiment yourself, but clicking on History, going to a prior commit, and then clicking View - it'll show you how it was after that older commit. I can't get any of them to render. That's why I think it's github's bug.

**Comment by stas00** [comment]
And another report from yesterday: https://github.com/GoogleCloudPlatform/cloudml-samples/issues/281
