### ISSUE TITLE
import of core.py fails

### ISSUE THREAD

**Issue by shirishr** [fastai/fastai#912]
from dataclasses import dataclass, field

fails

ModuleNotFoundError: No module named 'dataclasses'

**Comment by stas00** [comment]
fastai 1.0.x installation issues should be reported/discussed [here](http://forums.fast.ai/t/fastai-v1-install-issues-thread/24111) instead. Thank you.

When you do:

Please send the output of:
`python -c "import fastai; fastai.show_install()"
`

and the exact installation steps you did (since they are several ways).
